const T={
ru:{navWhy:"Почему ESCAPE",navAgent:"AI Agent",navWorld:"Весь мир",navCommunity:"Сообщество",navContact:"Контакты",heroTop:"Иногда поездку<br>даже не нужно<br>планировать.",heroBottom:"предложит идею сам.",heroText:"Свободные выходные, хорошая погода и ваши интересы — Escape сам предложит, куда поехать, когда выехать и что посмотреть по дороге.",heroCta:"Попробовать бесплатно",liveText:"Маршрут обновлён · всё под контролем",solutionsTitle:"Один запрос — десятки решений",solutionsText:"Маршрут, билеты, отель, авто, зарядки для EV, погода, пересадки, кафе и даже компания для поездки — Escape берёт всё под контроль.",f1t:"Маршруты",f1p:"Умные идеи под ваш стиль путешествий",f2t:"Билеты",f2p:"Авиа, поезд, автобус — быстро и удобно",f3t:"Отели",f3p:"Подбор жилья по комфорту и бюджету",f4t:"Авто",f4p:"Аренда авто и EV для вашего маршрута",f5t:"Погода",f5p:"Прогноз с учётом вашего дня",f6t:"Рекомендации",f6p:"Кафе, активности, места и компания",agentLabel:"AI АГЕНТ",agentTitle:"Ваш личный<br>помощник в путешествиях",a1:"Понимает ваши желания",a2:"Находит лучшие варианты",a3:"Помогает бронировать и строит маршрут",a4:"Поддерживает и сопровождает 24/7",communityLabel:"СООБЩЕСТВО",communityTitle:"Путешествуйте вместе",communityText:"Находите попутчиков, делитесь маршрутами и вдохновляйте других на новые приключения.",join:"Присоединиться",scenarioLabel:"ПОПУЛЯРНЫЕ СЦЕНАРИИ",scenarioTitle:"Путешествие под ваш сценарий",scenarioText:"От короткого уикенда до сложного EV road trip — Escape собирает всё в один понятный план.",s1t:"Уикенд у моря",s1p:"2–3 дня у побережья с лучшими пляжами и вкусной едой.",s2p:"Маршруты с зарядками, живописными местами и комфортом.",s3t:"Городские выходные",s3p:"Культура, достопримечательности и локальные секреты.",s4t:"Путешествие по Европе",s4p:"Поезда, пересадки, билеты и отели — всё в одном приложении.",ideas:"Посмотреть идеи →",benefitsTitle:"Почему путешественники выбирают Escape",b1t:"Быстро и легко",b1p:"Всё в одном приложении",b2t:"Надёжно",b2p:"Проверенные сервисы и защита данных",b3t:"Под вас",b3p:"Персональные идеи и рекомендации",b4t:"Всегда рядом",b4p:"Поддержка и сопровождение 24/7",b5t:"Сообщество",b5p:"Попутчики и друзья в путешествиях",b6t:"Весь мир",b6p:"Тысячи направлений и возможностей",servicesLabel:"ВСЁ ПОД РУКОЙ",servicesTitle:"Мы работаем с ведущими travel-сервисами",servicesNote:"Названия сервисов приведены как примеры экосистемы и не означают официальное партнёрство, если оно отдельно не заявлено.",contactTitle:"готовится к запуску.",contactText:"Для партнёрств, вопросов по продукту и обращений по данным используйте email.",support:"Поддержка: 10:00–19:00 UTC+3",footerProduct:"Продукт",footerFeatures:"Возможности",footerHow:"Как это работает",footerCompany:"Компания",footerAbout:"О нас",footerCareer:"Карьера",footerPartners:"Для партнёров",footerSupport:"Поддержка",footerHelp:"Центр помощи",footerLegal:"Правовая информация",rights:"Все права защищены.",soon:"Скоро доступно"},
uk:{navWhy:"Чому ESCAPE",navAgent:"AI Agent",navWorld:"Увесь світ",navCommunity:"Спільнота",navContact:"Контакти",heroTop:"Іноді поїздку<br>навіть не потрібно<br>планувати.",heroBottom:"сам запропонує ідею.",heroText:"Вільні вихідні, гарна погода та ваші інтереси — Escape сам запропонує, куди поїхати, коли виїхати і що подивитися дорогою.",heroCta:"Спробувати безкоштовно",liveText:"Маршрут оновлено · усе під контролем",solutionsTitle:"Один запит — десятки рішень",solutionsText:"Маршрут, квитки, готель, авто, зарядки для EV, погода, пересадки, кафе і навіть компанія для поїздки — Escape бере все під контроль.",f1t:"Маршрути",f1p:"Розумні ідеї під ваш стиль подорожей",f2t:"Квитки",f2p:"Авіа, потяг, автобус — швидко і зручно",f3t:"Готелі",f3p:"Підбір житла за комфортом і бюджетом",f4t:"Авто",f4p:"Оренда авто та EV для вашого маршруту",f5t:"Погода",f5p:"Прогноз з урахуванням вашого дня",f6t:"Рекомендації",f6p:"Кафе, активності, місця і компанія",agentLabel:"AI АГЕНТ",agentTitle:"Ваш особистий<br>помічник у подорожах",a1:"Розуміє ваші бажання",a2:"Знаходить найкращі варіанти",a3:"Допомагає бронювати та будує маршрут",a4:"Підтримує та супроводжує 24/7",communityLabel:"СПІЛЬНОТА",communityTitle:"Подорожуйте разом",communityText:"Знаходьте попутників, діліться маршрутами та надихайте інших на нові пригоди.",join:"Приєднатися",scenarioLabel:"ПОПУЛЯРНІ СЦЕНАРІЇ",scenarioTitle:"Подорож під ваш сценарій",scenarioText:"Від короткого вікенду до складного EV road trip — Escape збирає все в один зрозумілий план.",s1t:"Вікенд біля моря",s1p:"2–3 дні біля узбережжя з найкращими пляжами та смачною їжею.",s2p:"Маршрути із зарядками, мальовничими місцями та комфортом.",s3t:"Міські вихідні",s3p:"Культура, пам’ятки та локальні секрети.",s4t:"Подорож Європою",s4p:"Потяги, пересадки, квитки й готелі — усе в одному застосунку.",ideas:"Переглянути ідеї →",benefitsTitle:"Чому мандрівники обирають Escape",b1t:"Швидко й легко",b1p:"Усе в одному застосунку",b2t:"Надійно",b2p:"Перевірені сервіси та захист даних",b3t:"Під вас",b3p:"Персональні ідеї та рекомендації",b4t:"Завжди поруч",b4p:"Підтримка й супровід 24/7",b5t:"Спільнота",b5p:"Попутники та друзі в подорожах",b6t:"Увесь світ",b6p:"Тисячі напрямків і можливостей",servicesLabel:"УСЕ ПІД РУКОЮ",servicesTitle:"Ми працюємо з провідними travel-сервісами",servicesNote:"Назви сервісів наведені як приклади екосистеми й не означають офіційне партнерство, якщо його окремо не заявлено.",contactTitle:"готується до запуску.",contactText:"Для партнерств, питань щодо продукту та звернень щодо даних використовуйте email.",support:"Підтримка: 10:00–19:00 UTC+3",footerProduct:"Продукт",footerFeatures:"Можливості",footerHow:"Як це працює",footerCompany:"Компанія",footerAbout:"Про нас",footerCareer:"Кар’єра",footerPartners:"Для партнерів",footerSupport:"Підтримка",footerHelp:"Центр допомоги",footerLegal:"Правова інформація",rights:"Усі права захищені.",soon:"Незабаром доступно"},
en:{navWhy:"Why ESCAPE",navAgent:"AI Agent",navWorld:"Anywhere",navCommunity:"Community",navContact:"Contact",heroTop:"Sometimes you don't<br>even need to<br>plan the trip.",heroBottom:"suggests the idea.",heroText:"A free weekend, good weather and your interests — Escape can suggest where to go, when to leave and what to see on the way.",heroCta:"Try it free",liveText:"Route updated · everything under control",solutionsTitle:"One request — dozens of decisions",solutionsText:"Route, tickets, hotel, car, EV charging, weather, transfers, cafés and even people to travel with — Escape keeps it together.",f1t:"Routes",f1p:"Smart ideas for your travel style",f2t:"Tickets",f2p:"Flights, rail and bus — fast and convenient",f3t:"Hotels",f3p:"Stay selection by comfort and budget",f4t:"Car",f4p:"Rental cars and EV for your route",f5t:"Weather",f5p:"A forecast that fits your day",f6t:"Recommendations",f6p:"Cafés, activities, places and company",agentLabel:"AI AGENT",agentTitle:"Your personal<br>travel assistant",a1:"Understands what you want",a2:"Finds the best options",a3:"Helps with bookings and builds the route",a4:"Supports and guides you 24/7",communityLabel:"COMMUNITY",communityTitle:"Travel together",communityText:"Find travel companions, share routes and inspire others to new adventures.",join:"Join",scenarioLabel:"POPULAR SCENARIOS",scenarioTitle:"Travel built around your scenario",scenarioText:"From a short weekend to a complex EV road trip — Escape turns it into one clear plan.",s1t:"Weekend by the sea",s1p:"2–3 days by the coast with great beaches and food.",s2p:"Routes with charging, scenic places and comfort.",s3t:"City weekend",s3p:"Culture, landmarks and local secrets.",s4t:"Travel across Europe",s4p:"Trains, transfers, tickets and hotels — all in one app.",ideas:"Explore ideas →",benefitsTitle:"Why travelers choose Escape",b1t:"Fast and easy",b1p:"Everything in one app",b2t:"Reliable",b2p:"Trusted services and data protection",b3t:"Made for you",b3p:"Personalized ideas and recommendations",b4t:"Always there",b4p:"Support and guidance 24/7",b5t:"Community",b5p:"Travel companions and friends",b6t:"The whole world",b6p:"Thousands of destinations and possibilities",servicesLabel:"EVERYTHING AT HAND",servicesTitle:"We work with leading travel services",servicesNote:"Service names are shown as examples of the travel ecosystem and do not imply an official partnership unless separately stated.",contactTitle:"is preparing for launch.",contactText:"For partnerships, product questions and data-related requests, use email.",support:"Support: 10:00–19:00 UTC+3",footerProduct:"Product",footerFeatures:"Features",footerHow:"How it works",footerCompany:"Company",footerAbout:"About",footerCareer:"Careers",footerPartners:"For partners",footerSupport:"Support",footerHelp:"Help center",footerLegal:"Legal",rights:"All rights reserved.",soon:"Coming soon"}
};
let lang=localStorage.getItem("escape-lang")||"ru";
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
function setLang(l){
  lang=l; localStorage.setItem("escape-lang",l); document.documentElement.lang=l;
  $$("[data-lang]").forEach(b=>b.classList.toggle("active",b.dataset.lang===l));
  $$("[data-i18n]").forEach(el=>{const v=T[l]?.[el.dataset.i18n]; if(v!==undefined) el.textContent=v});
  $$("[data-html]").forEach(el=>{const v=T[l]?.[el.dataset.html]; if(v!==undefined) el.innerHTML=v});
}
$$("[data-lang]").forEach(b=>b.addEventListener("click",()=>setLang(b.dataset.lang)));
setLang(lang);

const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add("show")}),{threshold:.08});
$$(".reveal").forEach(e=>io.observe(e));

const nav=$("#mainNav"), menu=$("#menuBtn");
menu?.addEventListener("click",()=>nav.classList.toggle("open"));
$$("#mainNav a").forEach(a=>a.addEventListener("click",()=>nav.classList.remove("open")));

let toastTimer;
function showToast(msg){const t=$("#toast");t.textContent=msg;t.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove("show"),1800)}
$$("[data-soon]").forEach(b=>b.addEventListener("click",()=>showToast(T[lang].soon)));