const LEGAL={
privacy:{
en:{title:"Privacy Policy",meta:"Effective: 28 August 2026 · Pre-launch website",body:`
<p class="legal-note">ESCAPE is currently presented as a pre-launch product. This policy describes escapetravel.site as it exists now. If accounts, payments, analytics, precise location services or the mobile application are introduced, this policy will be updated before those features are used.</p>
<h2>1. What we collect now</h2><p>The public website does not currently provide user accounts, checkout, trip booking or a contact form. The site stores your selected language locally in your browser. Our hosting provider may process standard technical logs such as IP address, browser/device information, request time and requested URL for security, availability and network operation.</p>
<h2>2. Information you provide</h2><p>If you contact us by telephone, WhatsApp or another external channel, the information you send is processed through that provider and used to respond to your request or discuss partnerships.</p>
<h2>3. Location and travel data</h2><p>The current website does not request precise device location or collect itinerary data. Future ESCAPE app features may require location, trip preferences, routes and travel context. Appropriate disclosures and permissions will be provided before collection.</p>
<h2>4. How information may be used</h2><ul><li>operate, secure and maintain the website;</li><li>remember language preferences;</li><li>respond to communications;</li><li>detect abuse, outages or technical issues;</li><li>comply with applicable legal obligations.</li></ul>
<h2>5. Third parties</h2><p>The site uses third-party hosting infrastructure and links to services such as WhatsApp and external sources. Those providers operate under their own privacy policies.</p>
<h2>6. Retention and rights</h2><p>Language preference remains on your device until site storage is cleared. Technical logs and communications are retained only as reasonably necessary. Depending on your jurisdiction, you may have rights of access, correction, deletion, restriction or objection.</p>
<h2>7. Children</h2><p>The site is not intended to knowingly collect personal data from children. Future community features will require dedicated age, safety and moderation rules before launch.</p>
<h2>8. Contact</h2><p>ESCAPE / AI Travel Agent<br>Website: escapetravel.site<br>Phone / WhatsApp: +30 693 722 3454</p>
<h2>9. Updates</h2><p>This policy may be updated as the product evolves.</p>`},
ru:{title:"Политика конфиденциальности",meta:"Действует с 28 августа 2026 · Pre-launch сайт",body:`
<p class="legal-note">ESCAPE сейчас находится на стадии pre-launch. Эта политика описывает сайт escapetravel.site в его текущем виде. Перед запуском аккаунтов, платежей, аналитики, точной геолокации или мобильного приложения политика будет обновлена.</p>
<h2>1. Какие данные мы собираем сейчас</h2><p>На публичном сайте сейчас нет пользовательских аккаунтов, оплаты, бронирования поездок или контактной формы. Сайт сохраняет выбранный язык локально в вашем браузере. Хостинг-провайдер может обрабатывать стандартные технические журналы: IP-адрес, сведения о браузере/устройстве, время запроса и запрошенный URL — для безопасности и работы сети.</p>
<h2>2. Информация, которую вы предоставляете</h2><p>Если вы связываетесь с нами по телефону, WhatsApp или через другой внешний канал, отправленные вами данные обрабатываются соответствующим сервисом и используются для ответа или обсуждения сотрудничества.</p>
<h2>3. Геолокация и данные о поездках</h2><p>Текущий сайт не запрашивает точную геолокацию устройства и не собирает маршруты. Будущим функциям приложения ESCAPE могут потребоваться геолокация, предпочтения, маршруты и контекст поездки. До начала такого сбора будут предоставлены необходимые уведомления и разрешения.</p>
<h2>4. Для чего могут использоваться данные</h2><ul><li>для работы, безопасности и поддержки сайта;</li><li>для сохранения языковых предпочтений;</li><li>для ответа на обращения;</li><li>для выявления злоупотреблений и технических проблем;</li><li>для соблюдения применимого законодательства.</li></ul>
<h2>5. Третьи стороны</h2><p>Сайт использует стороннюю инфраструктуру хостинга и содержит ссылки на WhatsApp и внешние источники. Такие поставщики действуют в соответствии со своими политиками конфиденциальности.</p>
<h2>6. Хранение и ваши права</h2><p>Выбор языка хранится на устройстве, пока вы не очистите данные сайта. Технические журналы и переписка хранятся только разумно необходимый срок. В зависимости от юрисдикции вы можете иметь право на доступ, исправление, удаление, ограничение обработки или возражение.</p>
<h2>7. Дети</h2><p>Сайт не предназначен для намеренного сбора персональных данных детей. До запуска community-функций будут введены отдельные правила возраста, безопасности и модерации.</p>
<h2>8. Контакты</h2><p>ESCAPE / AI Travel Agent<br>Сайт: escapetravel.site<br>Телефон / WhatsApp: +30 693 722 3454</p>
<h2>9. Обновления</h2><p>Политика может обновляться по мере развития продукта.</p>`},
uk:{title:"Політика конфіденційності",meta:"Чинна з 28 серпня 2026 · Pre-launch сайт",body:`
<p class="legal-note">ESCAPE наразі перебуває на стадії pre-launch. Ця політика описує escapetravel.site у його поточному вигляді. Перед запуском акаунтів, платежів, аналітики, точної геолокації або мобільного застосунку політика буде оновлена.</p>
<h2>1. Які дані ми збираємо зараз</h2><p>На публічному сайті зараз немає користувацьких акаунтів, оплати, бронювання подорожей або контактної форми. Сайт зберігає вибрану мову локально у вашому браузері. Хостинг-провайдер може обробляти стандартні технічні журнали: IP-адресу, дані браузера/пристрою, час запиту та URL — для безпеки та роботи мережі.</p>
<h2>2. Інформація, яку ви надаєте</h2><p>Якщо ви зв’язуєтеся з нами телефоном, WhatsApp або через інший зовнішній канал, надіслані дані обробляються відповідним сервісом і використовуються для відповіді або обговорення співпраці.</p>
<h2>3. Геолокація та дані про подорожі</h2><p>Поточний сайт не запитує точну геолокацію пристрою і не збирає маршрути. Майбутнім функціям ESCAPE можуть знадобитися геолокація, уподобання, маршрути й контекст подорожі. До початку такого збору будуть надані необхідні повідомлення та дозволи.</p>
<h2>4. Для чого можуть використовуватися дані</h2><ul><li>для роботи, безпеки та підтримки сайту;</li><li>для збереження мовних уподобань;</li><li>для відповіді на звернення;</li><li>для виявлення зловживань і технічних проблем;</li><li>для дотримання застосовного законодавства.</li></ul>
<h2>5. Треті сторони</h2><p>Сайт використовує сторонню інфраструктуру хостингу та містить посилання на WhatsApp і зовнішні джерела. Такі постачальники працюють за власними політиками конфіденційності.</p>
<h2>6. Зберігання та ваші права</h2><p>Вибір мови зберігається на пристрої, доки ви не очистите дані сайту. Технічні журнали та листування зберігаються лише розумно необхідний строк. Залежно від юрисдикції ви можете мати право на доступ, виправлення, видалення, обмеження або заперечення.</p>
<h2>7. Діти</h2><p>Сайт не призначений для свідомого збору персональних даних дітей. До запуску community-функцій будуть введені окремі правила віку, безпеки та модерації.</p>
<h2>8. Контакти</h2><p>ESCAPE / AI Travel Agent<br>Сайт: escapetravel.site<br>Телефон / WhatsApp: +30 693 722 3454</p>
<h2>9. Оновлення</h2><p>Політика може оновлюватися разом із розвитком продукту.</p>`}
},
terms:{
en:{title:"Terms of Use",meta:"Effective: 28 August 2026 · Pre-launch website",body:`
<p class="legal-note">ESCAPE is currently a pre-launch concept website. Features shown illustrate intended capabilities and may change before commercial release.</p>
<h2>1. Acceptance</h2><p>By using escapetravel.site you agree to these Terms.</p>
<h2>2. No booking service at this stage</h2><p>The current website does not itself sell flights, hotels, transport or travel packages and does not execute bookings. Route planning, live assistance, community, payment or partner features shown here describe planned capabilities.</p>
<h2>3. Travel information</h2><p>Schedules, prices, border and visa rules, weather, road conditions, charging availability and opening hours can change quickly. Verify time-sensitive information with authoritative sources.</p>
<h2>4. User responsibility</h2><p>You remain responsible for documents, visas, insurance, tickets, check-in, boarding times, local laws, driving rules, reservations and personal safety.</p>
<h2>5. Third-party services</h2><p>Airlines, hotels, transport providers, maps, booking platforms and payment services are governed by their own terms. ESCAPE is not responsible for independent third-party cancellations, pricing changes or service failures.</p>
<h2>6. AI limitations</h2><p>AI can misunderstand requests or produce incomplete or inaccurate information. See the AI & Travel Disclaimer.</p>
<h2>7. Community</h2><p>Future Travel Together features will require dedicated community rules, reporting, moderation, privacy controls and safety measures. Users remain responsible for decisions about meeting or travelling with others.</p>
<h2>8. Intellectual property</h2><p>The ESCAPE name, website design, interface concepts, text, graphics and original materials are protected by applicable law unless otherwise stated.</p>
<h2>9. Prohibited use</h2><ul><li>disrupting, probing or misusing the website;</li><li>unlawful, fraudulent or harmful use;</li><li>misrepresenting affiliation with ESCAPE;</li><li>commercial copying without authorization.</li></ul>
<h2>10. Warranties and liability</h2><p>The pre-launch site is provided “as is” and “as available” to the maximum extent permitted by law. Nothing excludes liability that cannot lawfully be excluded.</p>
<h2>11. Changes and contact</h2><p>Commercial launch, payments, accounts or booking functionality will require updated terms. Contact: +30 693 722 3454.</p>`},
ru:{title:"Условия использования",meta:"Действуют с 28 августа 2026 · Pre-launch сайт",body:`
<p class="legal-note">ESCAPE сейчас является pre-launch сайтом концепции продукта. Показанные функции отражают планируемые возможности и могут измениться до коммерческого запуска.</p>
<h2>1. Принятие условий</h2><p>Используя escapetravel.site, вы соглашаетесь с настоящими Условиями.</p>
<h2>2. На данном этапе это не сервис бронирования</h2><p>Текущий сайт сам не продаёт авиабилеты, отели, транспорт или туристические пакеты и не выполняет бронирования. Планирование маршрутов, live-сопровождение, community, платежи и партнёрские функции описывают планируемые возможности.</p>
<h2>3. Информация о путешествиях</h2><p>Расписания, цены, визовые и пограничные правила, погода, дороги, зарядные станции и часы работы быстро меняются. Важную по времени информацию необходимо проверять по авторитетным источникам.</p>
<h2>4. Ответственность пользователя</h2><p>Вы сами отвечаете за документы, визы, страховку, билеты, check-in, посадку, местные законы, правила вождения, бронирования и личную безопасность.</p>
<h2>5. Сторонние сервисы</h2><p>Авиакомпании, отели, транспортные провайдеры, карты, booking-платформы и платежные сервисы работают по собственным условиям. ESCAPE не отвечает за независимые отмены, изменение цен или сбои третьих сторон.</p>
<h2>6. Ограничения AI</h2><p>AI может неправильно понять запрос, использовать неполные данные или дать неточную рекомендацию. См. AI & Travel Disclaimer.</p>
<h2>7. Сообщество</h2><p>Будущие функции Travel Together потребуют отдельных правил сообщества, жалоб, модерации, приватности и мер безопасности. Пользователь самостоятельно принимает решение о встрече или совместной поездке.</p>
<h2>8. Интеллектуальная собственность</h2><p>Название ESCAPE, дизайн сайта, интерфейсные концепции, тексты, графика и оригинальные материалы защищаются применимым законодательством.</p>
<h2>9. Запрещённое использование</h2><ul><li>нарушение работы или попытки взлома сайта;</li><li>незаконное, мошенническое или вредоносное использование;</li><li>ложное представление о связи с ESCAPE;</li><li>коммерческое копирование без разрешения.</li></ul>
<h2>10. Гарантии и ответственность</h2><p>Pre-launch сайт предоставляется «как есть» и «по мере доступности» в максимально допустимой законом степени. Ничто не ограничивает ответственность, которую закон запрещает исключать.</p>
<h2>11. Изменения и контакты</h2><p>До коммерческого запуска, платежей, аккаунтов или бронирований условия будут обновлены. Контакт: +30 693 722 3454.</p>`},
uk:{title:"Умови використання",meta:"Чинні з 28 серпня 2026 · Pre-launch сайт",body:`
<p class="legal-note">ESCAPE зараз є pre-launch сайтом концепції продукту. Показані функції відображають заплановані можливості та можуть змінитися до комерційного запуску.</p>
<h2>1. Прийняття умов</h2><p>Використовуючи escapetravel.site, ви погоджуєтеся з цими Умовами.</p>
<h2>2. На цьому етапі це не сервіс бронювання</h2><p>Поточний сайт сам не продає авіаквитки, готелі, транспорт або туристичні пакети й не виконує бронювань. Планування маршрутів, live-супровід, community, платежі та партнерські функції описують заплановані можливості.</p>
<h2>3. Інформація про подорожі</h2><p>Розклади, ціни, візові та прикордонні правила, погода, дороги, зарядні станції та години роботи швидко змінюються. Важливу за часом інформацію потрібно перевіряти за авторитетними джерелами.</p>
<h2>4. Відповідальність користувача</h2><p>Ви самі відповідаєте за документи, візи, страхування, квитки, check-in, посадку, місцеві закони, правила водіння, бронювання та особисту безпеку.</p>
<h2>5. Сторонні сервіси</h2><p>Авіакомпанії, готелі, транспортні провайдери, карти, booking-платформи та платіжні сервіси працюють за власними умовами. ESCAPE не відповідає за незалежні скасування, зміну цін або збої третіх сторін.</p>
<h2>6. Обмеження AI</h2><p>AI може неправильно зрозуміти запит, використати неповні дані або дати неточну рекомендацію. Див. AI & Travel Disclaimer.</p>
<h2>7. Спільнота</h2><p>Майбутні функції Travel Together потребуватимуть окремих правил спільноти, скарг, модерації, приватності та заходів безпеки. Користувач самостійно приймає рішення про зустріч або спільну поїздку.</p>
<h2>8. Інтелектуальна власність</h2><p>Назва ESCAPE, дизайн сайту, інтерфейсні концепції, тексти, графіка й оригінальні матеріали захищаються застосовним законодавством.</p>
<h2>9. Заборонене використання</h2><ul><li>порушення роботи або спроби злому сайту;</li><li>незаконне, шахрайське або шкідливе використання;</li><li>неправдиве представлення про зв’язок з ESCAPE;</li><li>комерційне копіювання без дозволу.</li></ul>
<h2>10. Гарантії та відповідальність</h2><p>Pre-launch сайт надається «як є» та «за наявності» у максимально дозволеному законом обсязі. Ніщо не обмежує відповідальність, яку закон забороняє виключати.</p>
<h2>11. Зміни та контакти</h2><p>До комерційного запуску, платежів, акаунтів або бронювань умови будуть оновлені. Контакт: +30 693 722 3454.</p>`}
},
cookies:{
en:{title:"Cookie Policy",meta:"Effective: 28 August 2026 · Pre-launch website",body:`<p class="legal-note">ESCAPE does not intentionally use advertising or behavioral-tracking cookies on this public website.</p><h2>1. Local storage</h2><p>The site uses browser local storage to remember your selected language (RU / UA / EN).</p><h2>2. Essential hosting technology</h2><p>Hosting and network providers may use essential mechanisms for security, routing, fraud prevention, load balancing or service operation.</p><h2>3. Analytics</h2><p>This release does not intentionally include a separate behavioral analytics or advertising script. If analytics, advertising or additional cookies are introduced, this policy and any required consent mechanism will be updated first.</p><h2>4. Managing storage</h2><p>You can clear site data through browser settings. Doing so may reset your language preference.</p><h2>5. Contact</h2><p>Phone / WhatsApp: +30 693 722 3454.</p>`},
ru:{title:"Политика Cookie",meta:"Действует с 28 августа 2026 · Pre-launch сайт",body:`<p class="legal-note">ESCAPE намеренно не использует на этом публичном сайте рекламные или поведенческие tracking-cookie.</p><h2>1. Локальное хранилище</h2><p>Сайт использует local storage браузера, чтобы запомнить выбранный язык (RU / UA / EN).</p><h2>2. Необходимые технологии хостинга</h2><p>Хостинг- и сетевые провайдеры могут использовать необходимые механизмы для безопасности, маршрутизации, защиты от злоупотреблений, балансировки нагрузки и работы сервиса.</p><h2>3. Аналитика</h2><p>В этой версии сайта намеренно нет отдельного скрипта поведенческой аналитики или рекламы. Если аналитика, реклама или дополнительные cookie будут добавлены, эта политика и необходимый механизм согласия будут обновлены заранее.</p><h2>4. Управление хранилищем</h2><p>Вы можете удалить данные сайта в настройках браузера. После этого языковое предпочтение может сброситься.</p><h2>5. Контакт</h2><p>Телефон / WhatsApp: +30 693 722 3454.</p>`},
uk:{title:"Політика Cookie",meta:"Чинна з 28 серпня 2026 · Pre-launch сайт",body:`<p class="legal-note">ESCAPE свідомо не використовує на цьому публічному сайті рекламні або поведінкові tracking-cookie.</p><h2>1. Локальне сховище</h2><p>Сайт використовує local storage браузера, щоб запам’ятати вибрану мову (RU / UA / EN).</p><h2>2. Необхідні технології хостингу</h2><p>Хостинг- і мережеві провайдери можуть використовувати необхідні механізми для безпеки, маршрутизації, захисту від зловживань, балансування навантаження та роботи сервісу.</p><h2>3. Аналітика</h2><p>У цій версії сайту свідомо немає окремого скрипта поведінкової аналітики або реклами. Якщо аналітика, реклама чи додаткові cookie будуть додані, ця політика та необхідний механізм згоди будуть оновлені заздалегідь.</p><h2>4. Керування сховищем</h2><p>Ви можете видалити дані сайту в налаштуваннях браузера. Після цього мовне уподобання може скинутися.</p><h2>5. Контакт</h2><p>Телефон / WhatsApp: +30 693 722 3454.</p>`}
},
disclaimer:{
en:{title:"AI & Travel Disclaimer",meta:"Effective: 28 August 2026 · Pre-launch website",body:`<p class="legal-note">ESCAPE is designed to reduce planning effort, not to replace authoritative travel, safety, legal, medical or immigration information.</p><h2>1. AI can be wrong</h2><p>Artificial intelligence may produce incomplete, outdated or incorrect information. Recommendations are assistance, not guarantees.</p><h2>2. Verify time-sensitive data</h2><p>Always verify flight and train times, gates, boarding, ferries, reservations, road closures, charging status, opening hours, prices and weather through authoritative or real-time sources.</p><h2>3. Borders, visas and documents</h2><p>Confirm immigration, visa, customs and entry requirements with official government or consular sources.</p><h2>4. Safety and health</h2><p>ESCAPE does not provide medical or emergency advice. Contact local emergency services when necessary.</p><h2>5. Driving and EV travel</h2><p>Range, charging speed and station availability depend on vehicle, weather, elevation, traffic and infrastructure. Drivers remain responsible for safe operation and contingency planning.</p><h2>6. Layovers</h2><p>Leaving an airport can involve immigration, security, baggage and queues. Use conservative buffers and verify airline and airport requirements.</p><h2>7. Community</h2><p>Future matching does not mean ESCAPE endorses or guarantees another user. Exercise independent judgment and personal-safety precautions.</p><h2>8. Pre-launch visuals</h2><p>Interface images are product concepts and design demonstrations, not proof that every shown feature or integration is currently available.</p>`},
ru:{title:"Дисклеймер AI и путешествий",meta:"Действует с 28 августа 2026 · Pre-launch сайт",body:`<p class="legal-note">ESCAPE создан, чтобы уменьшать объём ручного планирования, а не заменять официальную туристическую, правовую, медицинскую, миграционную или экстренную информацию.</p><h2>1. AI может ошибаться</h2><p>Искусственный интеллект может выдавать неполную, устаревшую или неверную информацию. Рекомендации являются помощью, а не гарантией.</p><h2>2. Проверяйте данные, зависящие от времени</h2><p>Всегда перепроверяйте рейсы, поезда, гейты, посадку, паромы, бронирования, перекрытия дорог, статус зарядок, часы работы, цены и погоду по официальным или real-time источникам.</p><h2>3. Границы, визы и документы</h2><p>Иммиграционные, визовые, таможенные и въездные требования проверяйте по официальным государственным или консульским источникам.</p><h2>4. Безопасность и здоровье</h2><p>ESCAPE не предоставляет медицинские или экстренные консультации. При необходимости обращайтесь в местные экстренные службы.</p><h2>5. Вождение и EV</h2><p>Запас хода, скорость зарядки и доступность станции зависят от автомобиля, погоды, рельефа, трафика и инфраструктуры. Водитель отвечает за безопасное управление и резервный план.</p><h2>6. Пересадки</h2><p>Выход из аэропорта может включать иммиграцию, безопасность, багаж и очереди. Используйте консервативные временные буферы и проверяйте требования авиакомпании и аэропорта.</p><h2>7. Сообщество</h2><p>Будущий matching не означает, что ESCAPE одобряет или гарантирует другого пользователя. Используйте собственную оценку риска и меры личной безопасности.</p><h2>8. Pre-launch визуалы</h2><p>Интерфейсы на сайте — концепты и дизайн-демонстрации, а не подтверждение, что каждая показанная функция или интеграция уже доступна.</p>`},
uk:{title:"Дисклеймер AI та подорожей",meta:"Чинний з 28 серпня 2026 · Pre-launch сайт",body:`<p class="legal-note">ESCAPE створений, щоб зменшувати обсяг ручного планування, а не замінювати офіційну туристичну, правову, медичну, міграційну чи екстрену інформацію.</p><h2>1. AI може помилятися</h2><p>Штучний інтелект може видавати неповну, застарілу або неправильну інформацію. Рекомендації є допомогою, а не гарантією.</p><h2>2. Перевіряйте дані, залежні від часу</h2><p>Завжди перевіряйте рейси, потяги, гейти, посадку, пороми, бронювання, перекриття доріг, статус зарядок, години роботи, ціни та погоду за офіційними або real-time джерелами.</p><h2>3. Кордони, візи та документи</h2><p>Імміграційні, візові, митні та в’їзні вимоги перевіряйте за офіційними державними або консульськими джерелами.</p><h2>4. Безпека та здоров’я</h2><p>ESCAPE не надає медичних або екстрених консультацій. За потреби звертайтеся до місцевих екстрених служб.</p><h2>5. Водіння та EV</h2><p>Запас ходу, швидкість заряджання та доступність станції залежать від автомобіля, погоди, рельєфу, трафіку та інфраструктури. Водій відповідає за безпечне керування та резервний план.</p><h2>6. Пересадки</h2><p>Вихід з аеропорту може включати імміграцію, безпеку, багаж та черги. Використовуйте консервативні часові буфери та перевіряйте вимоги авіакомпанії й аеропорту.</p><h2>7. Спільнота</h2><p>Майбутній matching не означає, що ESCAPE схвалює або гарантує іншого користувача. Використовуйте власну оцінку ризику й заходи особистої безпеки.</p><h2>8. Pre-launch візуали</h2><p>Інтерфейси на сайті — концепти та дизайн-демонстрації, а не підтвердження, що кожна показана функція чи інтеграція вже доступна.</p>`}
}};
const LABELS={en:{privacy:"Privacy Policy",terms:"Terms of Use",cookies:"Cookie Policy",disclaimer:"AI & Travel Disclaimer",back:"← ESCAPE",footer:"Pre-launch product"},ru:{privacy:"Политика конфиденциальности",terms:"Условия использования",cookies:"Политика Cookie",disclaimer:"Дисклеймер AI и путешествий",back:"← ESCAPE",footer:"Pre-launch продукт"},uk:{privacy:"Політика конфіденційності",terms:"Умови використання",cookies:"Політика Cookie",disclaimer:"Дисклеймер AI та подорожей",back:"← ESCAPE",footer:"Pre-launch продукт"}};
const type=document.body.dataset.legal;
let lang=localStorage.getItem("escape-lang")||"ru";
function render(l){
  lang=l;localStorage.setItem("escape-lang",l);document.documentElement.lang=l;
  document.querySelectorAll("[data-lang]").forEach(b=>b.classList.toggle("active",b.dataset.lang===l));
  const data=LEGAL[type][l], labels=LABELS[l];
  document.title=data.title+" — ESCAPE";
  document.getElementById("legalTitle").textContent=data.title;
  document.getElementById("legalMeta").textContent=data.meta;
  document.getElementById("legalBody").innerHTML=data.body;
  document.getElementById("back").textContent=labels.back;
  document.getElementById("legalNav").innerHTML=["privacy","terms","cookies","disclaimer"].filter(x=>x!==type).map(x=>`<a href="${x}.html">${labels[x]}</a>`).join("");
  document.getElementById("legalFooter").textContent=`© 2026 ESCAPE · ${labels.footer}`;
}
document.querySelectorAll("[data-lang]").forEach(b=>b.onclick=()=>render(b.dataset.lang));render(lang);