const I18N={
ru:{
navProblem:"Почему ESCAPE",navAgent:"AI Agent",navWorld:"Весь мир",navCommunity:"Сообщество",navContact:"Контакты",
heroEyebrow:"ВАШЕ ПУТЕШЕСТВИЕ · ОДИН AI-АГЕНТ · 24/7",heroTitle:"<span class=\"accent-blue\">Скажите, куда хотите.</span><br><span class=\"accent-red\">ESCAPE сделает остальное.</span>",heroText:"Один запрос вместо десятка вкладок: маршрут, билеты, отель, автомобиль, EV‑зарядки, паромы, погода, кафе, достопримечательности, пересадки, время и даже компания для поездки.",heroCta:"Посмотреть, как это работает",soon:"СКОРО",statOne:"запрос",statTwo:"сопровождение",statThree:"полный путь",live:"LIVE TRAVEL AGENT",liveText:"Маршрут обновлён · всё по плану",
problemKicker:"МИР ПУТЕШЕСТВИЙ ОГРОМЕН. ПЛАНИРОВАНИЕ ВСЁ ЕЩЁ РАЗДРОБЛЕНО.",problemTitle:"<span class=\"small-line\">Сегодня одна поездка — это</span><br><span class=\"big-line\">Booking, Skyscanner, карты, погода, расписания</span><br><span class=\"accent-red\">и десятки решений.</span>",problemText:"Вы сравниваете рейсы, ищете отель, считаете время до аэропорта, проверяете пересадку, парковку, паром, зарядку, погоду и запас времени. Если поездка сложная — количество решений растёт в разы. ESCAPE объединяет этот процесс в один диалог и один живой план.",m1:"международных туристических прибытий в 2024",m2:"вклад Travel & Tourism в мировой GDP в 2025",m3:"электромобилей продано в мире в 2025",m4:"сервисов легко открыть для одной сложной поездки",m4s:"типичный пользовательский сценарий",coreText:"Один агент собирает решение целиком",sourcesLabel:"Источники:",
agentTitle:"<span class=\"small-line\">Не ещё один планировщик.</span><br><span class=\"big-line\">Агент, который остаётся с вами</span><br><span class=\"accent-blue\">всю поездку.</span>",agentText:"ESCAPE не заканчивает работу после кнопки «Построить маршрут». Он сопровождает вас до возвращения домой: напоминает, предупреждает, пересчитывает и подсказывает в нужный момент.",a1t:"Контролирует время",a1p:"Понимает, сколько реально есть времени на пересадку, когда выйти и когда пора возвращаться к гейту.",a2t:"Учитывает погоду",a2p:"Если через час дождь — перестроит прогулку так, чтобы сначала увидеть то, что лучше смотреть под открытым небом.",a3t:"Перестраивает маршрут",a3p:"Задержка, пробка, закрытая зарядка или изменение рейса — агент пересчитает следующий шаг.",a4t:"Заботится о деталях",a4p:"Подскажет, где поесть рядом, когда лучше отдохнуть, что посмотреть и какой вариант будет комфортнее именно сейчас.",
flowTitle:"<span class=\"big-line\">Один запрос.</span> <span class=\"accent-blue\">Готовое путешествие.</span>",s1t:"Вы говорите цель",s1p:"Куда, когда, с кем, бюджет, автомобиль, багаж и ваши пожелания.",s2t:"AI сравнивает варианты",s2p:"Самолёт, авто, поезд, паром, такси, пешком, отели и зарядки.",s3t:"Вы получаете решение",s3p:"Время, стоимость, риски, буферы, карта, остановки и лучший сценарий.",s4t:"ESCAPE ведёт вас live",s4p:"Уведомления, погода, задержки, советы и перестройка на ходу.",s5t:"И возвращает домой",s5p:"Обратная логистика уже является частью путешествия.",
evTitle:"2,862 км. Зарядки, паромы, границы — <span class=\"accent-blue\">в одном маршруте.</span>",evText:"Для EV‑маршрута агент учитывает реальный запас хода, быстрые и резервные станции, паромы, границы, ночёвки, отдых, стоимость и обратный путь.",ev1:"основные и резервные зарядки",ev2:"паромы, границы и временные окна",ev3:"ночёвки, остановки, бюджет и буферы",
parisTitle:"Париж вдвоём — <span class=\"accent-blue\">весь день уже продуман.</span>",parisText:"Район, отель, завтрак, дорога из аэропорта, прогулка, ужин, метро и время — всё собирается в один понятный день.",parisQuote:"«Не спешите: завтрак до 10:30. После него лучше пройтись пешком через красивый квартал. На вечер — ужин в семи минутах от отеля.»",
amsTitle:"Амстердам — <span class=\"accent-blue\">как провести день без лишней суеты.</span>",amsText:"Где оставить машину, когда пересесть на велосипед, во сколько пойти в музей и нужен ли зонт — решения зависят от конкретного дня.",amsQuote:"«После 16:00 дождь. Машину лучше оставить на P+R, до центра — на велосипеде, музей — до обеда.»",
worldTitle:"<span class=\"accent-blue\">Любая точка мира.</span><br>Только скажите, чего вы хотите.",worldText:"Большой город, остров, road trip, горы, семейный отпуск или сложная пересадка. ESCAPE строит не «типовой тур», а маршрут вокруг вашей цели.",w1t:"Город на 48 часов",w1p:"Рейс, район, отель, транспорт, прогулки и рестораны.",w2t:"Road trip",w2p:"Дороги, зарядки, паромы, границы, ночёвки и красивые остановки.",w3t:"Семейный отпуск",w3p:"Комфорт, дети, безопасность, логистика, питание и свободное время.",w4t:"Сложная пересадка",w4p:"Можно ли выйти в город, сколько времени есть и когда возвращаться.",
weekTitle:"Иногда поездку даже не нужно планировать.<br><span class=\"accent-red\">ESCAPE предложит идею сам.</span>",weekText:"Свободные выходные, хорошая погода и ваши интересы — ESCAPE сам предложит, куда поехать, когда выехать и что посмотреть по дороге.",pushT:"☀ Отличная погода на выходных",pushP:"В радиусе 50 км есть несколько красивых мест. Хотите, соберу маршрут на день с хорошим местом для заката?",
commTitle:"<span class=\"small-line\">Не просто смотреть чужие поездки.</span><br><span class=\"big-line\">Создавайте свои и находите</span><br><span class=\"accent-red\">людей, которым с вами по пути.</span>",commText:"Опубликуйте маршрут, найдите попутчиков, другую семью для совместной поездки или компанию для road trip. Сообщество строится вокруг реальных планов, а не просто контента.",communityBadge:"TRAVEL TOGETHER",communityBadgeSub:"найдите людей для следующей поездки",c1t:"🚗 Есть машина?",c1p:"Опубликуйте маршрут, найдите компанию и при желании разделите расходы.",c2t:"👨‍👩‍👧 Семейная поездка?",c2p:"Другие семьи, kid‑friendly места, пикники, парки и совместные идеи.",c3t:"🚐 RV / Vanlife?",c3p:"Стоянки, вода, душ, красивые маршруты и люди с тем же стилем путешествий.",c4t:"🌅 Просто хочется выбраться?",c4p:"ESCAPE покажет идеи и людей рядом, которые тоже хотят поехать.",n1:"Больше людей",n2:"Больше поездок",n3:"Больше совпадений",n4:"Сильнее сообщество",
pulseTitle:"Мир путешествует прямо сейчас.",pulseText:"Это не поток Booking.com. Это честная живая оценка, рассчитанная из последнего годового показателя UN Tourism — 1,52 млрд международных прибытий в 2025 году.",pulseLabel:"Оценка международных прибытий с момента открытия страницы",perSecondText:"международных прибытий в секунду в среднем",chartTitle:"Где путешествовал мир",chartText:"Региональная структура международных прибытий, млн человек. Данные UN Tourism, январь 2026.",kineticTitle:"<span class=\"small-line\">Вы ставите задачу.</span><br><span class=\"big-line\">ESCAPE сам собирает</span><br><span class=\"accent-red\">всю поездку.</span>",kineticText:"ESCAPE разбивает цель на транспорт, жильё, время, риски, погоду, бюджет и личные предпочтения — а затем снова собирает всё в единый маршрут.",contactTitle:"<span class=\"accent-blue\">ESCAPE</span> готовится к запуску.",contactText:"Для партнёрств, вопросов по продукту и обращений по данным используйте email. Телефон и домашний адрес публично не размещаются.",contactOwnerLabel:"OWNER / CONTACT",contactHours:"Поддержка: 10:00–19:00 UTC+3",contactCountry:"Greece · EU",privacy:"Privacy Policy",terms:"Terms of Use",cookies:"Cookie Policy",disclaimer:"AI & Travel Disclaimer",prelaunch:"Pre-launch product"
},
uk:{
navProblem:"Чому ESCAPE",navAgent:"AI Agent",navWorld:"Увесь світ",navCommunity:"Спільнота",navContact:"Контакти",
heroEyebrow:"ВАША ПОДОРОЖ · ОДИН AI-АГЕНТ · 24/7",heroTitle:"<span class=\"accent-blue\">Скажіть, куди хочете.</span><br><span class=\"accent-red\">ESCAPE зробить решту.</span>",heroText:"Один запит замість десятка вкладок: маршрут, квитки, готель, автомобіль, EV‑зарядки, пороми, погода, кафе, пам’ятки, пересадки, час і навіть компанія для поїздки.",heroCta:"Подивитися, як це працює",soon:"НЕЗАБАРОМ",statOne:"запит",statTwo:"супровід",statThree:"повний шлях",live:"LIVE TRAVEL AGENT",liveText:"Маршрут оновлено · усе за планом",
problemKicker:"СВІТ ПОДОРОЖЕЙ ВЕЛИЧЕЗНИЙ. ПЛАНУВАННЯ ДОСІ РОЗДРОБЛЕНЕ.",problemTitle:"<span class=\"small-line\">Сьогодні одна поїздка — це</span><br><span class=\"big-line\">Booking, Skyscanner, карти, погода, розклади</span><br><span class=\"accent-red\">і десятки рішень.</span>",problemText:"Ви порівнюєте рейси, шукаєте готель, рахуєте час до аеропорту, перевіряєте пересадку, паркування, пором, зарядку, погоду та запас часу. Якщо поїздка складна — кількість рішень зростає в рази. ESCAPE об’єднує цей процес в один діалог і один живий план.",m1:"міжнародних туристичних прибуттів у 2024",m2:"внесок Travel & Tourism у світовий GDP у 2025",m3:"електромобілів продано у світі у 2025",m4:"сервісів легко відкрити для однієї складної поїздки",m4s:"типовий користувацький сценарій",coreText:"Один агент збирає рішення цілком",sourcesLabel:"Джерела:",
agentTitle:"<span class=\"small-line\">Не ще один планувальник.</span><br><span class=\"big-line\">Агент, який залишається з вами</span><br><span class=\"accent-blue\">всю подорож.</span>",agentText:"ESCAPE не завершує роботу після кнопки «Побудувати маршрут». Він супроводжує вас до повернення додому: нагадує, попереджає, перераховує та підказує у потрібний момент.",a1t:"Контролює час",a1p:"Розуміє, скільки реально є часу на пересадку, коли вийти й коли час повертатися до гейту.",a2t:"Враховує погоду",a2p:"Якщо за годину дощ — перебудує прогулянку так, щоб спочатку побачити те, що краще дивитися надворі.",a3t:"Перебудовує маршрут",a3p:"Затримка, затор, закрита зарядка або зміна рейсу — агент перерахує наступний крок.",a4t:"Дбає про деталі",a4p:"Підкаже, де поїсти поруч, коли краще відпочити, що подивитися і який варіант комфортніший саме зараз.",
flowTitle:"<span class=\"big-line\">Один запит.</span> <span class=\"accent-blue\">Готова подорож.</span>",s1t:"Ви говорите мету",s1p:"Куди, коли, з ким, бюджет, автомобіль, багаж і ваші побажання.",s2t:"AI порівнює варіанти",s2p:"Літак, авто, потяг, пором, таксі, пішки, готелі та зарядки.",s3t:"Ви отримуєте рішення",s3p:"Час, вартість, ризики, буфери, карта, зупинки та найкращий сценарій.",s4t:"ESCAPE веде вас live",s4p:"Сповіщення, погода, затримки, поради та перебудова в дорозі.",s5t:"І повертає додому",s5p:"Зворотна логістика вже є частиною подорожі.",
evTitle:"2 862 км. Зарядки, пороми, кордони — <span class=\"accent-blue\">в одному маршруті.</span>",evText:"Для EV‑маршруту агент враховує реальний запас ходу, швидкі й резервні станції, пороми, кордони, ночівлі, відпочинок, вартість і зворотний шлях.",ev1:"основні й резервні зарядки",ev2:"пороми, кордони та часові вікна",ev3:"ночівлі, зупинки, бюджет і буфери",
parisTitle:"Париж удвох — <span class=\"accent-blue\">увесь день уже продуманий.</span>",parisText:"Район, готель, сніданок, дорога з аеропорту, прогулянка, вечеря, метро й час — усе збирається в один зрозумілий день.",parisQuote:"«Не поспішайте: сніданок до 10:30. Після нього краще пройтися пішки через красивий квартал. На вечір — вечеря за сім хвилин від готелю.»",
amsTitle:"Амстердам — <span class=\"accent-blue\">як провести день без зайвої метушні.</span>",amsText:"Де залишити авто, коли пересісти на велосипед, о котрій піти до музею та чи потрібна парасоля — рішення залежать від конкретного дня.",amsQuote:"«Після 16:00 дощ. Авто краще залишити на P+R, до центру — велосипедом, музей — до обіду.»",
worldTitle:"<span class=\"accent-blue\">Будь-яка точка світу.</span><br>Просто скажіть, чого ви хочете.",worldText:"Велике місто, острів, road trip, гори, сімейна відпустка або складна пересадка. ESCAPE будує не «типовий тур», а маршрут навколо вашої мети.",w1t:"Місто на 48 годин",w1p:"Рейс, район, готель, транспорт, прогулянки й ресторани.",w2t:"Road trip",w2p:"Дороги, зарядки, пороми, кордони, ночівлі та красиві зупинки.",w3t:"Сімейна відпустка",w3p:"Комфорт, діти, безпека, логістика, харчування й вільний час.",w4t:"Складна пересадка",w4p:"Чи можна вийти в місто, скільки часу є та коли повертатися.",
weekTitle:"Іноді поїздку навіть не треба планувати.<br><span class=\"accent-red\">ESCAPE сам запропонує ідею.</span>",weekText:"Вільні вихідні, гарна погода й ваші інтереси — ESCAPE сам запропонує, куди поїхати, коли виїхати та що подивитися дорогою.",pushT:"☀ Чудова погода на вихідних",pushP:"У радіусі 50 км є кілька красивих місць. Хочете, зберу маршрут на день із хорошим місцем для заходу сонця?",
commTitle:"<span class=\"small-line\">Не просто дивитися чужі поїздки.</span><br><span class=\"big-line\">Створюйте свої та знаходьте</span><br><span class=\"accent-red\">людей, яким з вами по дорозі.</span>",commText:"Опублікуйте маршрут, знайдіть попутників, іншу сім’ю для спільної поїздки або компанію для road trip. Спільнота будується навколо реальних планів, а не просто контенту.",communityBadge:"TRAVEL TOGETHER",communityBadgeSub:"знайдіть людей для наступної поїздки",c1t:"🚗 Є авто?",c1p:"Опублікуйте маршрут, знайдіть компанію і за бажанням розділіть витрати.",c2t:"👨‍👩‍👧 Сімейна поїздка?",c2p:"Інші сім’ї, kid‑friendly місця, пікніки, парки та спільні ідеї.",c3t:"🚐 RV / Vanlife?",c3p:"Стоянки, вода, душ, красиві маршрути й люди з тим самим стилем подорожей.",c4t:"🌅 Просто хочеться вибратися?",c4p:"ESCAPE покаже ідеї та людей поруч, які теж хочуть поїхати.",n1:"Більше людей",n2:"Більше поїздок",n3:"Більше збігів",n4:"Сильніша спільнота",
pulseTitle:"Світ подорожує просто зараз.",pulseText:"Це не потік Booking.com. Це чесна жива оцінка, розрахована з останнього річного показника UN Tourism — 1,52 млрд міжнародних прибуттів у 2025 році.",pulseLabel:"Оцінка міжнародних прибуттів від моменту відкриття сторінки",perSecondText:"міжнародних прибуттів за секунду в середньому",chartTitle:"Де подорожував світ",chartText:"Регіональна структура міжнародних прибуттів, млн людей. Дані UN Tourism, січень 2026.",kineticTitle:"<span class=\"small-line\">Ви ставите задачу.</span><br><span class=\"big-line\">ESCAPE сам збирає</span><br><span class=\"accent-red\">усю подорож.</span>",kineticText:"ESCAPE розкладає мету на транспорт, житло, час, ризики, погоду, бюджет і особисті вподобання — а потім знову збирає все в єдиний маршрут.",contactTitle:"<span class=\"accent-blue\">ESCAPE</span> готується до запуску.",contactText:"Для партнерств, питань щодо продукту та звернень щодо даних використовуйте email. Телефон і домашня адреса публічно не розміщуються.",contactOwnerLabel:"OWNER / CONTACT",contactHours:"Підтримка: 10:00–19:00 UTC+3",contactCountry:"Greece · EU",privacy:"Privacy Policy",terms:"Terms of Use",cookies:"Cookie Policy",disclaimer:"AI & Travel Disclaimer",prelaunch:"Pre-launch product"
},
en:{
navProblem:"Why ESCAPE",navAgent:"AI Agent",navWorld:"Anywhere",navCommunity:"Community",navContact:"Contact",
heroEyebrow:"YOUR JOURNEY · ONE AI AGENT · 24/7",heroTitle:"<span class=\"accent-blue\">Tell us where you want to go.</span><br><span class=\"accent-red\">ESCAPE handles the rest.</span>",heroText:"One request instead of ten tabs: route, tickets, hotel, car, EV charging, ferries, weather, cafés, sights, transfers, timing and even people to travel with.",heroCta:"See how it works",soon:"COMING SOON",statOne:"request",statTwo:"live support",statThree:"complete journey",live:"LIVE TRAVEL AGENT",liveText:"Route updated · everything on track",
problemKicker:"TRAVEL IS MASSIVE. PLANNING IS STILL FRAGMENTED.",problemTitle:"<span class=\"small-line\">One trip today can mean</span><br><span class=\"big-line\">Booking, Skyscanner, maps, weather and timetables</span><br><span class=\"accent-red\">plus dozens of decisions.</span>",problemText:"You compare flights, find a hotel, calculate airport time, check a layover, parking, ferry, charging, weather and buffers. The more complex the trip, the more decisions you need to make. ESCAPE turns that process into one conversation and one live plan.",m1:"international tourist arrivals in 2024",m2:"Travel & Tourism contribution to global GDP in 2025",m3:"electric cars sold globally in 2025",m4:"services you can easily open for one complex trip",m4s:"typical user journey",coreText:"One agent assembles the complete decision",sourcesLabel:"Sources:",
agentTitle:"<span class=\"small-line\">Not another planner.</span><br><span class=\"big-line\">An agent that stays with you</span><br><span class=\"accent-blue\">for the whole journey.</span>",agentText:"ESCAPE does not stop after “Build route”. It stays with you until you get home — reminding, warning, recalculating and helping at the exact moment you need it.",a1t:"Manages your time",a1p:"Understands how much time you really have on a layover, when to leave and when to head back to the gate.",a2t:"Adapts to weather",a2p:"If rain starts in an hour, it rearranges the walk so outdoor highlights come first.",a3t:"Replans live",a3p:"Delay, traffic, an unavailable charger or a changed flight — the agent recalculates the next step.",a4t:"Cares about the details",a4p:"Where to eat nearby, when to rest, what to see and which option is more comfortable right now.",
flowTitle:"<span class=\"big-line\">One request.</span> <span class=\"accent-blue\">One complete journey.</span>",s1t:"You state the goal",s1p:"Where, when, with whom, budget, car, luggage and preferences.",s2t:"AI compares options",s2p:"Flight, car, train, ferry, taxi, walking, hotels and charging.",s3t:"You get the decision",s3p:"Time, cost, risks, buffers, map, stops and the best scenario.",s4t:"ESCAPE guides you live",s4p:"Notifications, weather, delays, advice and real-time replanning.",s5t:"And gets you home",s5p:"Return logistics are already part of the trip.",
evTitle:"2,862 km. Chargers, ferries, borders — <span class=\"accent-blue\">one route.</span>",evText:"For an EV route, the agent accounts for real range, fast and backup chargers, ferries, borders, overnight stops, rest, cost and the return journey.",ev1:"primary and backup charging",ev2:"ferries, borders and critical timing windows",ev3:"overnights, stops, budget and buffers",
parisTitle:"Paris for two — <span class=\"accent-blue\">the whole day already thought through.</span>",parisText:"Area, hotel, breakfast, airport transfer, walk, dinner, metro and timing become one coherent day.",parisQuote:"“No need to rush: breakfast is open until 10:30. Then take a scenic walk through the neighborhood. Dinner is seven minutes from your hotel.”",
amsTitle:"Amsterdam — <span class=\"accent-blue\">how to spend the day without the hassle.</span>",amsText:"Where to park, when to switch to a bike, when to visit the museum and whether to bring an umbrella — the answer depends on that specific day.",amsQuote:"“Rain after 16:00. Leave the car at P+R, bike into the center and visit the museum before lunch.”",
worldTitle:"<span class=\"accent-blue\">Anywhere in the world.</span><br>Just tell us what you want.",worldText:"A major city, an island, a road trip, mountains, a family holiday or a complex layover. ESCAPE does not build a generic tour — it builds around your goal.",w1t:"48 hours in a city",w1p:"Flight, area, hotel, transport, walks and restaurants.",w2t:"Road trip",w2p:"Roads, charging, ferries, borders, overnights and scenic stops.",w3t:"Family holiday",w3p:"Comfort, kids, safety, logistics, food and free time.",w4t:"Complex layover",w4p:"Can you visit the city, how much time do you have and when should you return?",
weekTitle:"Sometimes you do not even need to plan.<br><span class=\"accent-red\">ESCAPE suggests the idea.</span>",weekText:"A free weekend, good weather and your interests — ESCAPE suggests where to go, when to leave and what to see on the way.",pushT:"☀ Great weather this weekend",pushP:"There are several beautiful places within 50 km. Want me to build a day route with a great sunset spot?",
commTitle:"<span class=\"small-line\">Do not just watch other people travel.</span><br><span class=\"big-line\">Create your own trip and find</span><br><span class=\"accent-red\">people going your way.</span>",commText:"Publish your route, find travel companions, another family for a shared trip or people for a road trip. The community is built around real plans, not just content.",communityBadge:"TRAVEL TOGETHER",communityBadgeSub:"find people for your next journey",c1t:"🚗 Have a car?",c1p:"Publish your route, find company and optionally split costs.",c2t:"👨‍👩‍👧 Family trip?",c2p:"Other families, kid-friendly places, picnics, parks and shared ideas.",c3t:"🚐 RV / Vanlife?",c3p:"Stops, water, showers, beautiful routes and people with the same travel style.",c4t:"🌅 Just want to get away?",c4p:"ESCAPE shows ideas and nearby people who want to go too.",n1:"More people",n2:"More trips",n3:"More matches",n4:"Stronger community",
pulseTitle:"The world is travelling right now.",pulseText:"This is not a Booking.com feed. It is a transparent live estimate derived from UN Tourism’s latest annual baseline: 1.52 billion international arrivals in 2025.",pulseLabel:"Estimated international arrivals since you opened this page",perSecondText:"international arrivals per second on average",chartTitle:"Where the world travelled",chartText:"International arrivals by region, millions. UN Tourism data, January 2026.",kineticTitle:"<span class=\"small-line\">You set the goal.</span><br><span class=\"big-line\">ESCAPE assembles</span><br><span class=\"accent-red\">the whole journey.</span>",kineticText:"ESCAPE decomposes the goal into transport, accommodation, time, risk, weather, budget and personal preferences — then rebuilds everything into one coherent journey.",contactTitle:"<span class=\"accent-blue\">ESCAPE</span> is preparing for launch.",contactText:"For partnerships, product questions and data-related requests, use email. Phone and home address are not published.",contactOwnerLabel:"OWNER / CONTACT",contactHours:"Support: 10:00–19:00 UTC+3",contactCountry:"Greece · EU",privacy:"Privacy Policy",terms:"Terms of Use",cookies:"Cookie Policy",disclaimer:"AI & Travel Disclaimer",prelaunch:"Pre-launch product"
}};
let lang=localStorage.getItem("escape-lang")||"ru";
function setLang(l){
  lang=l; localStorage.setItem("escape-lang",l); document.documentElement.lang=l;
  document.querySelectorAll("[data-lang]").forEach(b=>b.classList.toggle("active",b.dataset.lang===l));
  document.querySelectorAll("[data-t]").forEach(el=>{const v=I18N[l]?.[el.dataset.t]; if(v!==undefined) el.innerHTML=v;});
}
document.querySelectorAll("[data-lang]").forEach(b=>b.onclick=()=>setLang(b.dataset.lang));
setLang(lang);
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add("show")}),{threshold:.11});
document.querySelectorAll(".reveal").forEach(e=>io.observe(e));
addEventListener("scroll",()=>{
  const h=document.documentElement, denom=h.scrollHeight-h.clientHeight;
  const p=denom>0?h.scrollTop/denom*100:0;
  const bar=document.querySelector(".progress"); if(bar) bar.style.width=p+"%";
});
// Transparent "live" travel pulse based on 1.52B international arrivals in 2025.
// This is a modelled average, not a real-time booking or platform feed.
(function(){
  const annual=1520000000;
  const perSec=annual/(365*24*60*60);
  const started=performance.now();
  const counter=document.getElementById("liveArrivalCounter");
  const ps=document.getElementById("perSecond");
  if(ps) ps.textContent="≈"+Math.round(perSec);
  function tick(){
    if(counter){
      const elapsed=(performance.now()-started)/1000;
      counter.textContent=Math.floor(elapsed*perSec).toLocaleString(document.documentElement.lang||"en");
    }
    requestAnimationFrame(tick);
  }
  tick();
})();
